server:
  port: 8080
  servlet:
    session:
      timeout: 120m # 세션 유지시간 120분으로 증가

spring:
  elasticsearch:
    uris: http://my-elasticSearch:9200 # Docker Compose에서 설정한 컨테이너 이름 사용
    username: elastic
    password: ${ELASTIC_PASSWORD}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3306/recipidia?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: health

logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /index.html

host:
  url: ${HOST_URL}

fastapi:
  base:
    url: ${FASTAPI_API_URL}
  header:
    xapi: ${X_API}

login:
  admin:
    pw: ${ADMIN_PW}
